<div class="sidebar">
    <nav>
        <ul>
            <li><a href="home.php"><i class="fas fa-tachometer"></i>&nbsp;&nbsp;Dashboard</a></li>
            <li><a href="usermanagement.php"><i class="fa-solid fa-users"></i>&nbsp;&nbsp;App Users</a></li>
            <li><a href="jobmanagement.php"><i class="fa-solid fa-briefcase"></i>&nbsp;&nbsp;Jobs Board</a></li>
            <li><a href="cvtemplates.php"><i class="fas fa-file-contract"></i>&nbsp;&nbsp;CV Templates</a></li>
        </ul>
    </nav> 
</div>