<div class="sidebar">
    <nav>
        <ul>
            <li><a href="home.php"><i class="fa-solid fa-house-user"></i></i>&nbsp;&nbsp;Home</a></li>
            <li><a href="usermanagement.php"><i class="fa-solid fa-users"></i>&nbsp;&nbsp;App Users/management</a></li>
            <li><a href="jobmanagement.php"><i class="fa-solid fa-briefcase"></i>&nbsp;&nbsp;Jobs Management</a></li>
        </ul>
    </nav> 
</div>