<form class="contactForm" method="post">
    <div class="row">
        <div class="col-lg-4">
            <label for="password">Password</label><br />
            <input type="pasword" name="password" />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <label for="repass">Rewrite Password</label><br />
            <input type="pasword" name="repass" />
        </div>
    </div>
    <br />
    <input type="submit" class="submit" name="submit" value="Save CV" />
</form>