<div class="sidebar">
    <nav>
        <ul>
            <li><a href="home.php"><i class="fa-solid fa-house-user"></i></i>&nbsp;&nbsp;Home</a></li>
            <li><a href="cvmanagement.php"><i class="fa-solid fa-file-circle-check"></i>&nbsp;&nbsp;My CVs</a></li>
            <li><a href="careers.php"><i class="fa-solid fa-person-circle-plus"></i>&nbsp;&nbsp;Job Board</a></li>
        </ul>
    </nav> 
</div>